#!/usr/bin/env python3
"""Generate the awesome lists in awesome/ from the project catalog in catalog/.

Each catalog/<slug>.md carries frontmatter (repo, url, summary, categories[],
features[], tags[], status, interest[], watch_*). This script groups entries by
category and writes one awesome/<category>.md per category, plus an
awesome/README.md index. Stdlib only — the CI gate needs no pip install.

Usage:
  build-catalog.py            regenerate awesome/*.md
  build-catalog.py --check    exit 1 if any awesome file is stale/orphaned (CI)
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CATALOG_DIR = os.path.join(ROOT, "catalog")
AWESOME_DIR = os.path.join(ROOT, "awesome")

VALID_STATUS = {"watching", "evaluating", "adopted", "rejected", "archived"}
GEN_MARKER = "<!-- GENERATED by scripts/build-catalog.py — DO NOT hand-edit. Run `python3 scripts/build-catalog.py`. -->"


def _scalar_or_list(v: str):
    """Parse a frontmatter value: an inline [a, b, c] list or a bare scalar."""
    v = v.strip()
    if v.startswith("[") and v.endswith("]"):
        inner = v[1:-1].strip()
        if not inner:
            return []
        return [x.strip().strip('"').strip("'") for x in inner.split(",") if x.strip()]
    return v.strip().strip('"').strip("'")


def parse_frontmatter(path: str) -> dict | None:
    """Return the frontmatter dict for a catalog entry, or None if it has none."""
    with open(path, encoding="utf-8") as f:
        if f.readline().strip() != "---":
            return None
        meta: dict = {}
        for line in f:
            if line.strip() == "---":
                return meta
            if ":" in line and not line.startswith((" ", "\t", "#")):
                k, _, v = line.partition(":")
                meta[k.strip()] = _scalar_or_list(v)
    return None  # unterminated frontmatter


def category_slug(cat: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", cat.strip().lower()).strip("-")


def category_title(cat: str) -> str:
    return cat.replace("-", " ").replace("_", " ").strip().title()


def discover() -> list[dict]:
    entries = []
    if not os.path.isdir(CATALOG_DIR):
        return entries
    for name in sorted(os.listdir(CATALOG_DIR)):
        if not name.endswith(".md") or name == "README.md":
            continue
        meta = parse_frontmatter(os.path.join(CATALOG_DIR, name))
        if not meta or not meta.get("repo"):
            print(f"WARN: {name} has no frontmatter/repo — skipping", file=sys.stderr)
            continue
        for field in ("categories", "features", "tags", "interest"):
            if isinstance(meta.get(field), str):  # a single unbracketed value
                meta[field] = [meta[field]] if meta[field] else []
            meta.setdefault(field, [])
        if not meta.get("categories"):
            print(f"WARN: {meta['repo']} has no categories — won't appear in any list", file=sys.stderr)
        status = meta.get("status", "")
        if status and status not in VALID_STATUS:
            print(f"WARN: {meta['repo']} status {status!r} not in {sorted(VALID_STATUS)}", file=sys.stderr)
        entries.append(meta)
    return entries


def _fmt(v) -> str:
    return ", ".join(v) if isinstance(v, list) else str(v)


def _plural(n: int, singular: str, plural: str) -> str:
    return f"{n} {singular if n == 1 else plural}"


def render_category(cat: str, entries: list[dict]) -> str:
    rows = ["| Project | Summary | Features | Status |", "|---|---|---|---|"]
    for e in sorted(entries, key=lambda x: x.get("repo", "")):
        repo = e.get("repo", "")
        url = e.get("url") or f"https://github.com/{repo}"
        rows.append(
            f"| [{repo}]({url}) | {e.get('summary', '')} | {_fmt(e.get('features', []))} | {e.get('status', '')} |"
        )
    return "\n".join([
        GEN_MARKER,
        f"# {category_title(cat)}",
        "",
        f"{_plural(len(entries), 'project', 'projects')}.",
        "",
        *rows,
        "",
    ])


def render_readme(by_cat: dict) -> str:
    lines = [
        GEN_MARKER,
        "# Awesome lists",
        "",
        "Curated, per-category lists of projects — generated from `catalog/` by "
        "`scripts/build-catalog.py`.",
        "",
    ]
    if not by_cat:
        lines += ["_No catalog entries yet. Add one from `templates/catalog-entry.md`._", ""]
        return "\n".join(lines)
    total = len({e["repo"] for entries in by_cat.values() for e in entries})
    lines.append(
        f"{_plural(total, 'project', 'projects')} across "
        f"{_plural(len(by_cat), 'category', 'categories')}."
    )
    lines.append("")
    for cat in sorted(by_cat):
        lines.append(f"- [{category_title(cat)}]({category_slug(cat)}.md) — {len(by_cat[cat])}")
    lines.append("")
    return "\n".join(lines)


def build() -> dict:
    """Return {relpath: content} for every awesome file that should exist."""
    entries = discover()
    by_cat: dict[str, list[dict]] = {}
    for e in entries:
        for cat in e.get("categories", []):
            by_cat.setdefault(cat, []).append(e)
    out = {os.path.join("awesome", "README.md"): render_readme(by_cat)}
    for cat, es in by_cat.items():
        out[os.path.join("awesome", f"{category_slug(cat)}.md")] = render_category(cat, es)
    return {k: (v if v.endswith("\n") else v + "\n") for k, v in out.items()}


def _existing_awesome() -> set[str]:
    if not os.path.isdir(AWESOME_DIR):
        return set()
    return {os.path.join("awesome", n) for n in os.listdir(AWESOME_DIR) if n.endswith(".md")}


def main() -> None:
    check = "--check" in sys.argv[1:]
    want = build()
    have = _existing_awesome()
    orphans = have - set(want)
    stale = []
    for rel, content in want.items():
        path = os.path.join(ROOT, rel)
        cur = open(path, encoding="utf-8").read() if os.path.exists(path) else ""
        if cur != content:
            stale.append(rel)

    if check:
        problems = stale + [f"{o} (orphaned)" for o in sorted(orphans)]
        if problems:
            print("awesome/ is stale — run `python3 scripts/build-catalog.py`:", file=sys.stderr)
            for p in problems:
                print(f"  - {p}", file=sys.stderr)
            sys.exit(1)
        print("awesome/ is up to date.")
        return

    os.makedirs(AWESOME_DIR, exist_ok=True)
    for rel, content in want.items():
        with open(os.path.join(ROOT, rel), "w", encoding="utf-8") as f:
            f.write(content)
    for rel in orphans:
        os.remove(os.path.join(ROOT, rel))
    print(f"wrote {len(want)} awesome file(s)"
          + (f", removed {len(orphans)} orphan(s)" if orphans else ""))


if __name__ == "__main__":
    main()
