#!/usr/bin/env python3
"""Build INDEX.md from the frontmatter of every report in the repo.

Walks the tree, reads each report's YAML frontmatter (subject/type/title/date/
sources), and writes a browsable index grouped by subject. Stdlib only — the CI
backstop needs no pip install.

Usage:
  build-index.py            regenerate INDEX.md
  build-index.py --check    exit 1 if INDEX.md is stale (CI gate), no write
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(ROOT, "INDEX.md")

# Directories and files that are never reports.
SKIP_DIRS = {".git", ".github", "scripts", "templates"}
SKIP_FILES = {"README.md", "INDEX.md", "AGENTS.md"}

TYPE_LABEL = {
    "summary": "Summary",
    "qa": "Q&A",
    "comparison": "Comparison",
    "security": "Security",
}


def parse_frontmatter(path):
    """Return the frontmatter dict for a markdown file, or None if it has none."""
    with open(path, encoding="utf-8") as f:
        first = f.readline()
        if first.strip() != "---":
            return None
        meta = {}
        for line in f:
            if line.strip() == "---":
                return meta
            if ":" in line:
                k, _, v = line.partition(":")
                meta[k.strip()] = v.strip().strip('"').strip("'")
    return None  # unterminated frontmatter → treat as none


def discover():
    reports = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for name in filenames:
            if not name.endswith(".md") or name in SKIP_FILES:
                continue
            path = os.path.join(dirpath, name)
            meta = parse_frontmatter(path)
            if not meta or "type" not in meta:
                continue
            rel = os.path.relpath(path, ROOT)
            reports.append((rel, meta))
    return reports


def render(reports):
    lines = [
        "<!-- GENERATED by scripts/build-index.py — DO NOT hand-edit. Run `python3 scripts/build-index.py`. -->",
        "# Index",
        "",
        f"{len(reports)} report(s) across {len({m.get('subject','?') for _, m in reports})} subject(s).",
        "",
    ]
    if not reports:
        lines += ["_No reports yet. Add one from `templates/` and re-run the generator._", ""]
        return "\n".join(lines)

    by_subject = {}
    for rel, meta in reports:
        by_subject.setdefault(meta.get("subject", "?"), []).append((rel, meta))

    for subject in sorted(by_subject):
        lines.append(f"## {subject}")
        lines.append("")
        lines.append("| Report | Type | Date | Sources |")
        lines.append("|---|---|---|---|")
        for rel, meta in sorted(by_subject[subject], key=lambda r: r[0]):
            title = meta.get("title", rel)
            typ = TYPE_LABEL.get(meta.get("type", ""), meta.get("type", ""))
            date = meta.get("date", "")
            src = meta.get("sources", "")
            lines.append(f"| [{title}]({rel}) | {typ} | {date} | {src} |")
        lines.append("")
    return "\n".join(lines)


def main():
    check = "--check" in sys.argv[1:]
    new = render(discover())
    if not new.endswith("\n"):
        new += "\n"
    existing = ""
    if os.path.exists(INDEX):
        with open(INDEX, encoding="utf-8") as f:
            existing = f.read()
    if check:
        if new != existing:
            print("INDEX.md is stale — run `python3 scripts/build-index.py`.", file=sys.stderr)
            sys.exit(1)
        print("INDEX.md is up to date.")
        return
    with open(INDEX, "w", encoding="utf-8") as f:
        f.write(new)
    print(f"wrote {os.path.relpath(INDEX, ROOT)}")


if __name__ == "__main__":
    main()
